# Generated by Django 5.0.1 on 2024-01-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_loser_alter_matches_winner'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lose_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_matches', to='players.player'),
        ),
    ]
