# Generated by Django 5.0.1 on 2024-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hand', models.CharField(choices=[('R', 'Rigth'), ('L', 'Left')], max_length=1)),
                ('country', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
